version: '3'

set:
  - errexit
  - nounset
  - pipefail

tasks:
  check:
    cmds:
      - deno fmt --check
      - deno lint
      - deno check src/cli.ts

  build:
    vars:
      VERSION: '{{.VERSION | default "unknown"}}'
      TARGETS:
        - x86_64-unknown-linux-gnu
        - aarch64-unknown-linux-gnu
        - x86_64-pc-windows-msvc
        - x86_64-apple-darwin
        - aarch64-apple-darwin
    cmds:
      - echo 'WK_VERSION="{{.VERSION}}"' > .env
      - for:
          var: TARGETS
          as: TARGET
        cmd: deno compile --no-check --cached-only --lock --frozen --env-file --allow-all --target {{.TARGET}} --include src/widget.eta --output dist/wk-{{.TARGET}} src/cli.ts
