name: Setup project
description: Setup project

runs:
  using: composite
  steps:
    - name: Setup mise
      uses: jdx/mise-action@v2
      with:
        version: 2025.9.25

    - name: Install dependencies
      shell: bash
      run: deno install
