name: Upload binaries

on:
  release:
    types:
      - published

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Run build
        run: VERSION=${{ github.event.release.tag_name }} mise run build

      - name: Upload binaries
        run: gh release upload ${{ github.event.release.tag_name }} dist/wk-*
        env:
          GH_TOKEN: ${{ github.token }}
